### ISSUE TITLE
works in fti browser but not in iconsmith or irix

### ISSUE THREAD

**Issue by psxpetey** [mach-kernel/svg2fti#1]
So here's the issue but first python 3.9 windows tinycss2 1.1.1 svg 4.0.2, When I use svg to fti the produced fti always works fine in fti browser but when I ftp it over to irix and try to open it it says error on line 2 syntax error. even using the nedit svg you provided. so heres a look at my nedit: # FTI generated by https://github.com/mach-kernel/svg2fti#Path 0
color(7);
bgnpolygon();
vertex(8.051858,44.963826);
vertex(8.140266,46.948369);
vertex(9.011796,49.985860);
vertex(10.550670,53.866927);
vertex(12.641110,58.382199);
vertex(15.167339,63.322303);
vertex(18.013579,68.477867);
vertex(21.064051,73.639519);
vertex(24.202978,78.597886);
vertex(27.314581,83.143597);
vertex(30.283084,87.067278);
vertex(32.992709,90.159558);
vertex(35.327676,92.211065);
vertex(37.174658,93.012680);
vertex(39.466358,92.690265);
vertex(42.748923,91.560634);
vertex(46.800953,89.758337);
vertex(51.401044,87.417924);
vertex(56.327796,84.673943);
vertex(61.359808,81.660944);
vertex(66.275677,78.513476);
vertex(70.854002,75.366089);
vertex(74.873382,72.353331);
vertex(78.112415,69.609752);
vertex(80.349700,67.269901);
vertex(81.363346,65.470335);
vertex(81.245767,63.409464);
vertex(80.328749,60.297821);
vertex(78.737822,56.347509);
vertex(76.598514,51.770634);
vertex(74.036354,46.779301);
vertex(71.176871,41.585615);
vertex(68.145593,36.401679);
vertex(65.068051,31.439600);
vertex(62.069771,26.911482);
vertex(59.276284,23.029429);
vertex(56.813117,20.005547);
vertex(54.805801,18.051940);
vertex(53.285279,17.356954);
vertex(50.989093,17.690306);
vertex(47.665119,18.832771);
vertex(43.541332,20.648917);
vertex(38.845709,23.003315);
vertex(33.806228,25.760532);
vertex(28.650865,28.785139);
vertex(23.607596,31.941704);
vertex(18.904398,35.094796);
vertex(14.769249,38.108986);
vertex(11.430125,40.848841);
vertex(8.051858,44.963826);
endoutlinepolygon(12);
#Path 1
color(12);
bgnpolygon();
vertex(43.916981,90.416997);
vertex(39.315717,85.752428);
vertex(32.555709,84.783757);
vertex(26.009915,83.379234);
vertex(20.237180,79.817301);
vertex(15.718342,74.727017);
vertex(10.899795,69.859406);
vertex(4.231523,68.878110);
vertex(0.035948,65.193002);
vertex(5.257338,60.605085);
vertex(11.157376,57.510233);
vertex(16.537638,53.423353);
vertex(22.856125,50.983614);
vertex(29.562425,49.809037);
vertex(31.576375,43.533350);
vertex(34.941404,37.480181);
vertex(40.131798,33.530559);
vertex(45.871216,34.245940);
vertex(44.505251,41.199329);
vertex(46.761949,46.640158);
vertex(52.817010,43.739597);
vertex(58.623412,40.139223);
vertex(62.146134,34.167205);
vertex(56.604838,32.120530);
vertex(51.620422,28.657820);
vertex(53.960696,22.372792);
vertex(59.290248,18.185850);
vertex(63.349609,12.912672);
vertex(65.122106,6.040883);
vertex(68.138420,0.000000);
vertex(73.361356,2.597773);
vertex(75.889091,8.849477);
vertex(76.858716,15.720317);
vertex(76.975795,22.494837);
vertex(75.601915,29.124395);
vertex(76.424218,35.497670);
vertex(77.679566,42.140284);
vertex(77.586845,48.900463);
vertex(76.242024,55.556117);
vertex(73.741071,61.885157);
vertex(70.179954,67.665493);
vertex(65.715586,72.779753);
vertex(60.505258,77.124252);
vertex(61.367023,82.624406);
vertex(60.649287,89.183597);
vertex(62.203443,96.091918);
vertex(59.524742,99.907731);
vertex(53.031119,98.546275);
vertex(47.464749,94.617137);
vertex(43.916981,90.416997);
pclos();
#Path 2
color(7);
bgnpolygon();
vertex(59.418299,97.797570);
vertex(60.172970,97.129363);
vertex(60.309261,96.433739);
vertex(60.007976,95.708084);
vertex(59.449922,94.949783);
vertex(58.815901,94.156222);
vertex(58.286721,93.324789);
vertex(58.043184,92.452868);
vertex(57.806619,92.023041);
vertex(56.971380,92.490659);
vertex(56.170851,92.978162);
vertex(55.387160,93.410357);
vertex(54.602439,93.712047);
vertex(53.798816,93.808038);
vertex(52.958424,93.623135);
vertex(52.063390,93.082142);
vertex(51.159101,92.793517);
vertex(50.288771,92.378157);
vertex(49.452267,91.832307);
vertex(48.650183,91.189362);
vertex(47.883112,90.482712);
vertex(47.151650,89.745753);
vertex(46.456390,89.011875);
vertex(45.797928,88.314473);
vertex(45.176857,87.686939);
vertex(44.593772,87.162666);
vertex(44.049266,86.775046);
vertex(43.705701,86.790633);
vertex(43.975513,87.663810);
vertex(44.309834,88.507445);
vertex(44.704312,89.321653);
vertex(45.154597,90.106551);
vertex(45.656338,90.862254);
vertex(46.205184,91.588877);
vertex(46.796785,92.286537);
vertex(47.426788,92.955348);
vertex(48.090843,93.595427);
vertex(48.784599,94.206889);
vertex(49.503705,94.789851);
vertex(50.243811,95.344426);
vertex(51.000565,95.870732);
vertex(51.769616,96.368884);
vertex(52.546613,96.838997);
vertex(53.327205,97.281187);
vertex(54.130161,97.659396);
vertex(54.990402,97.973682);
vertex(55.885564,98.217871);
vertex(56.795792,98.357158);
vertex(57.701228,98.356740);
vertex(59.418299,97.797570);
pclos();
#Path 3
color(7);
bgnpolygon();
vertex(40.956293,82.528877);
vertex(42.803410,82.213629);
vertex(44.648194,81.829424);
vertex(46.484821,81.375124);
vertex(48.307463,80.849592);
vertex(50.110295,80.251693);
vertex(51.887491,79.580289);
vertex(53.633226,78.834243);
vertex(55.341674,78.012420);
vertex(57.007008,77.113682);
vertex(58.623404,76.136892);
vertex(60.185036,75.080915);
vertex(61.686077,73.944612);
vertex(63.120702,72.726849);
vertex(64.483086,71.426487);
vertex(65.767402,70.042390);
vertex(66.967824,68.573421);
vertex(67.623002,66.540267);
vertex(66.827830,66.440881);
vertex(65.186067,67.655507);
vertex(63.356496,69.272725);
vertex(61.951423,70.415910);
vertex(60.373837,71.438981);
vertex(58.747571,72.398412);
vertex(57.076869,73.289745);
vertex(55.365974,74.108523);
vertex(53.619129,74.850287);
vertex(51.840576,75.510581);
vertex(50.034558,76.084946);
vertex(48.205319,76.568924);
vertex(46.357102,76.958057);
vertex(44.494149,77.247888);
vertex(42.620703,77.433959);
vertex(40.943863,76.826520);
vertex(39.457707,75.672398);
vertex(37.798665,75.295082);
vertex(36.022548,75.498634);
vertex(34.185166,76.087120);
vertex(32.342332,76.864604);
vertex(30.549856,77.635151);
vertex(28.696953,78.204574);
vertex(26.899093,79.174682);
vertex(26.454899,80.560610);
vertex(27.456384,81.710147);
vertex(29.668973,82.121728);
vertex(31.530878,82.439432);
vertex(33.409025,82.657261);
vertex(35.297025,82.775167);
vertex(37.188495,82.793104);
vertex(40.956293,82.528877);
pclos();
#Path 4
color(7);
bgnpolygon();
vertex(19.745075,77.178490);
vertex(19.423062,76.361147);
vertex(19.061033,75.562508);
vertex(18.660861,74.783018);
vertex(18.224421,74.023123);
vertex(17.753585,73.283266);
vertex(17.250226,72.563892);
vertex(16.716219,71.865447);
vertex(16.153437,71.188374);
vertex(15.563753,70.533120);
vertex(14.949040,69.900127);
vertex(14.311173,69.289842);
vertex(13.652024,68.702709);
vertex(12.973467,68.139172);
vertex(12.277375,67.599676);
vertex(11.565622,67.084667);
vertex(10.840081,66.594588);
vertex(10.102627,66.129885);
vertex(9.355131,65.691002);
vertex(9.007916,64.896186);
vertex(8.621262,64.224476);
vertex(7.960439,63.936983);
vertex(7.128090,63.967033);
vertex(6.226854,64.247952);
vertex(5.359373,64.713066);
vertex(4.628287,65.295702);
vertex(4.136239,65.929186);
vertex(3.985867,66.546844);
vertex(4.279815,67.082003);
vertex(5.120721,67.467989);
vertex(6.445452,67.630218);
vertex(7.353517,67.707566);
vertex(8.227284,67.865413);
vertex(9.068047,68.098130);
vertex(9.877102,68.400089);
vertex(10.655743,68.765661);
vertex(11.405265,69.189219);
vertex(12.126962,69.665133);
vertex(12.822128,70.187776);
vertex(13.492060,70.751518);
vertex(14.138050,71.350732);
vertex(14.761394,71.979789);
vertex(15.363387,72.633060);
vertex(15.945323,73.304917);
vertex(16.508496,73.989732);
vertex(17.054202,74.681877);
vertex(17.583735,75.375722);
vertex(18.090601,76.047499);
vertex(18.607318,76.637570);
vertex(19.745075,77.178490);
pclos();
#Path 5
color(7);
bgnpolygon();
vertex(26.766137,75.021417);
vertex(27.378079,74.748333);
vertex(27.839483,74.390469);
vertex(28.163696,73.962621);
vertex(28.364067,73.479585);
vertex(28.453942,72.956156);
vertex(28.446671,72.407131);
vertex(28.355602,71.847306);
vertex(28.194083,71.291475);
vertex(27.975461,70.754436);
vertex(27.713086,70.250985);
vertex(27.420304,69.795916);
vertex(27.110465,69.404026);
vertex(26.796917,69.090112);
vertex(26.493007,68.868968);
vertex(26.212084,68.755391);
vertex(25.967495,68.764177);
vertex(25.772590,68.910121);
vertex(25.640716,69.208020);
vertex(25.585221,69.672669);
vertex(25.619453,70.318864);
vertex(25.665683,71.138887);
vertex(25.545054,71.808785);
vertex(25.291540,72.274724);
vertex(24.928653,72.564030);
vertex(24.479903,72.704027);
vertex(23.968802,72.722043);
vertex(23.418861,72.645402);
vertex(22.853591,72.501430);
vertex(22.296503,72.317452);
vertex(21.771109,72.120794);
vertex(21.300921,71.938781);
vertex(20.909448,71.798740);
vertex(20.620202,71.727996);
vertex(20.456696,71.753873);
vertex(20.442439,71.903698);
vertex(20.600943,72.204797);
vertex(20.955719,72.684494);
vertex(21.467763,73.309375);
vertex(21.788990,73.702849);
vertex(22.144266,74.055595);
vertex(22.529938,74.366154);
vertex(22.942353,74.633061);
vertex(23.377858,74.854855);
vertex(23.832803,75.030074);
vertex(24.303533,75.157255);
vertex(24.786397,75.234936);
vertex(25.277741,75.261655);
vertex(25.773915,75.235950);
vertex(26.766137,75.021417);
pclos();
#Path 6
color(7);
bgnpolygon();
vertex(25.032019,68.148391);
vertex(25.777663,68.108691);
vertex(26.393290,67.954192);
vertex(26.875008,67.713414);
vertex(27.218925,67.414876);
vertex(27.421150,67.087097);
vertex(27.477789,66.758598);
vertex(27.384953,66.457898);
vertex(27.138747,66.213518);
vertex(26.735281,66.053975);
vertex(26.170663,66.007791);
vertex(25.441001,66.103485);
vertex(24.718739,66.320765);
vertex(24.235860,66.372598);
vertex(23.838187,66.244232);
vertex(23.501599,65.979958);
vertex(23.201974,65.624067);
vertex(22.915189,65.220850);
vertex(22.617123,64.814597);
vertex(22.283653,64.449599);
vertex(21.890659,64.170146);
vertex(21.414016,64.020530);
vertex(20.829604,64.045042);
vertex(20.113301,64.287971);
vertex(19.436980,64.301799);
vertex(18.836087,64.365149);
vertex(18.300592,64.524296);
vertex(17.834706,64.764371);
vertex(17.442637,65.070503);
vertex(17.128596,65.427822);
vertex(16.896793,65.821457);
vertex(16.751437,66.236537);
vertex(16.696739,66.658193);
vertex(16.736908,67.071553);
vertex(16.876154,67.461747);
vertex(17.118688,67.813905);
vertex(17.468718,68.113157);
vertex(17.930455,68.344630);
vertex(18.508109,68.493456);
vertex(19.205890,68.544764);
vertex(19.864815,68.540982);
vertex(20.383665,68.556749);
vertex(20.902804,68.558991);
vertex(21.421946,68.548193);
vertex(21.940805,68.524843);
vertex(22.459095,68.489427);
vertex(22.976531,68.442431);
vertex(23.492827,68.384343);
vertex(24.007698,68.315650);
vertex(25.032019,68.148391);
pclos();
#Path 7
color(7);
bgnpolygon();
vertex(34.167857,52.795107);
vertex(34.309282,52.009426);
vertex(34.445487,51.218385);
vertex(34.579294,50.423367);
vertex(34.713527,49.625757);
vertex(34.851011,48.826939);
vertex(34.994568,48.028297);
vertex(35.147023,47.231216);
vertex(35.311199,46.437080);
vertex(35.489920,45.647273);
vertex(35.686010,44.863180);
vertex(35.902292,44.086184);
vertex(36.141589,43.317671);
vertex(36.406726,42.559025);
vertex(36.700527,41.811629);
vertex(37.025815,41.076868);
vertex(37.385413,40.356127);
vertex(37.782145,39.650789);
vertex(38.218836,38.962240);
vertex(38.698308,38.291862);
vertex(39.445193,37.431792);
vertex(39.976556,36.592445);
vertex(40.014315,36.046933);
vertex(39.679742,35.791888);
vertex(39.094106,35.823945);
vertex(38.378678,36.139737);
vertex(37.654728,36.735898);
vertex(37.044435,37.557136);
vertex(36.528409,38.151704);
vertex(36.024172,38.770204);
vertex(35.534426,39.411141);
vertex(35.061868,40.073025);
vertex(34.609201,40.754362);
vertex(34.179123,41.453659);
vertex(33.774335,42.169423);
vertex(33.397537,42.900163);
vertex(33.051429,43.644384);
vertex(32.738710,44.400594);
vertex(32.462082,45.167301);
vertex(32.224243,45.943012);
vertex(32.027894,46.726234);
vertex(31.875736,47.515473);
vertex(31.770467,48.309239);
vertex(31.714789,49.106037);
vertex(31.711400,49.904374);
vertex(31.763002,50.702759);
vertex(31.872294,51.499699);
vertex(32.081688,52.278136);
vertex(32.649414,52.843764);
vertex(34.167857,52.795107);
pclos();
#Path 8
color(7);
bgnpolygon();
vertex(72.572214,31.901107);
vertex(73.047907,31.094588);
vertex(73.483893,30.269190);
vertex(73.880964,29.426339);
vertex(74.239911,28.567464);
vertex(74.561527,27.693989);
vertex(74.846602,26.807342);
vertex(75.095927,25.908949);
vertex(75.310294,25.000237);
vertex(75.490495,24.082633);
vertex(75.637320,23.157563);
vertex(75.751562,22.226454);
vertex(75.834011,21.290733);
vertex(75.885458,20.351826);
vertex(75.906696,19.411160);
vertex(75.898515,18.470161);
vertex(75.861707,17.530256);
vertex(75.797063,16.592873);
vertex(75.705375,15.659436);
vertex(75.587433,14.731374);
vertex(75.444030,13.810113);
vertex(75.275957,12.897079);
vertex(75.049942,11.915614);
vertex(74.578336,11.012127);
vertex(74.172244,11.097770);
vertex(73.854605,11.856156);
vertex(73.648359,12.970898);
vertex(73.576444,14.125610);
vertex(73.655713,15.023679);
vertex(73.703797,15.970920);
vertex(73.704366,16.911820);
vertex(73.660081,17.846367);
vertex(73.573601,18.774550);
vertex(73.447585,19.696359);
vertex(73.284693,20.611782);
vertex(73.087585,21.520808);
vertex(72.858921,22.423426);
vertex(72.601360,23.319625);
vertex(72.317561,24.209395);
vertex(72.010185,25.092723);
vertex(71.681890,25.969599);
vertex(71.335338,26.840013);
vertex(70.973186,27.703952);
vertex(70.598096,28.561406);
vertex(70.212725,29.412364);
vertex(69.847854,30.353550);
vertex(69.881873,31.311024);
vertex(70.257595,32.111027);
vertex(70.888745,32.587048);
vertex(72.572214,31.901107);
pclos();
#Path 9
color(7);
bgnpolygon();
vertex(56.965157,31.055196);
vertex(56.725553,30.990224);
vertex(56.481159,30.903845);
vertex(56.233516,30.796924);
vertex(55.984167,30.670329);
vertex(55.734650,30.524928);
vertex(55.486508,30.361587);
vertex(55.241280,30.181174);
vertex(55.000509,29.984555);
vertex(54.765734,29.772600);
vertex(54.538497,29.546173);
vertex(54.320338,29.306144);
vertex(54.112798,29.053379);
vertex(53.917419,28.788745);
vertex(53.735740,28.513109);
vertex(53.569303,28.227339);
vertex(53.419649,27.932302);
vertex(53.288318,27.628866);
vertex(53.176851,27.317897);
vertex(53.086790,27.000263);
vertex(53.019674,26.676831);
vertex(52.977045,26.348468);
vertex(52.960444,26.016041);
vertex(52.820900,26.271242);
vertex(52.697012,26.576622);
vertex(52.599331,26.886930);
vertex(52.527275,27.200392);
vertex(52.480258,27.515232);
vertex(52.457695,27.829676);
vertex(52.459002,28.141949);
vertex(52.483595,28.450276);
vertex(52.530889,28.752883);
vertex(52.600298,29.047996);
vertex(52.691240,29.333838);
vertex(52.803129,29.608636);
vertex(52.935380,29.870615);
vertex(53.087410,30.118000);
vertex(53.258633,30.349017);
vertex(53.448464,30.561890);
vertex(53.656321,30.754846);
vertex(53.881616,30.926108);
vertex(54.123768,31.073903);
vertex(54.382189,31.196456);
vertex(54.656297,31.291992);
vertex(54.945506,31.358737);
vertex(55.249232,31.394915);
vertex(55.566891,31.398752);
vertex(55.897897,31.368473);
vertex(56.241667,31.302304);
vertex(56.965157,31.055196);
pclos();

when I tag a script and install it there is an error in all lines and it cancels, What version of python 3 did you use?
any idea what the issue could be?

**Comment by mach-kernel** [comment]
The output looks OK, my first guess is Windows line endings. From WSL, or another machine with the `dos2unix` utility, can you try:

```
dos2unix output.fti
```

See if that works? I can update the code to prevent this if it's the case (probably)

**Comment by psxpetey** [comment]
ok that did work looks like that is the issue
